# Site settings
title: Jean-Paul van Houten - Bos Portfolio
email: formspree.io@vanhoutensolutions.nl
description: >-
  A simpele maar moderne website over Jean-Paul van Houten - Bos en zijn projecten.
baseurl: ""
url: "https://vanhoutenbos.github.io"

# Social links
github: "https://github.com/vanhoutenbos/"
linkedin: "https://www.linkedin.com/in/%F0%9F%92%BB-jean-paul-van-houten-bos-9254977a/"
stackoverflow: "https://stackoverflow.com/users/2604342/jean-paul"

# CAPTCHA removed: site will use honeypot + timestamp fallback instead of reCAPTCHA
# recaptcha_site_key and recaptcha_enabled removed per user request

# Build settings
markdown: kramdown
# Use Minimal Mistakes as a remote theme (works with GitHub Pages via jekyll-remote-theme)
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Repository (helpful for canonical URLs and GitHub Pages)
repository: vanhoutenbos/personal-website

# Public site URL (project pages normally live under /<repo>)
url: "https://vanhoutenbos.github.io/personal-website"

# Author / SEO defaults
author:
  name: "Jean-Paul van Houten - Bos"
  email: formspree.io@vanhoutensolutions.nl
  url: "https://vanhoutenbos.github.io/personal-website"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "nl"

# Default social image (place an image in assets/img/ if you add one)
image: "/assets/img/social-default.png"

# Locale
locale: "nl_NL"

# Exclude files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
