# Example _config.yml snippet for Analytics and SEO

# Add these lines to your _config.yml file to enable Google Analytics

# Google Analytics 4 (GA4)
# Get your Measurement ID from https://analytics.google.com
# Format: G-XXXXXXXXXX
google_analytics_id: "G-2WE7YD72NV"  # Replace with your actual Measurement ID

# That's it! Google Analytics will be automatically integrated when you deploy.
# The analytics.html include uses this value conditionally, so nothing loads if not configured.
